/* 
 * OAuth API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenResponseTests
    {
        // TODO uncomment below to declare an instance variable for TokenResponse
        //private TokenResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenResponse
            //instance = new TokenResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenResponse
        /// </summary>
        [Test]
        public void TokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenResponse
            //Assert.IsInstanceOfType<TokenResponse> (instance, "variable 'instance' is a TokenResponse");
        }


        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Test]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }
        /// <summary>
        /// Test the property 'RequiredAction'
        /// </summary>
        [Test]
        public void RequiredActionTest()
        {
            // TODO unit test for the property 'RequiredAction'
        }

    }

}
