/* 
 * OAuth API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TokenErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenErrorResponseTests
    {
        // TODO uncomment below to declare an instance variable for TokenErrorResponse
        //private TokenErrorResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenErrorResponse
            //instance = new TokenErrorResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenErrorResponse
        /// </summary>
        [Test]
        public void TokenErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenErrorResponse
            //Assert.IsInstanceOfType<TokenErrorResponse> (instance, "variable 'instance' is a TokenErrorResponse");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ErrorDescription'
        /// </summary>
        [Test]
        public void ErrorDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDescription'
        }
        /// <summary>
        /// Test the property 'ErrorUri'
        /// </summary>
        [Test]
        public void ErrorUriTest()
        {
            // TODO unit test for the property 'ErrorUri'
        }

    }

}
