/* 
 * Discovery API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model.Discovery
{
    /// <summary>
    /// ServicesDiscoveryResponse
    /// </summary>
    [DataContract]
    public partial class ServicesDiscoveryResponse :  IEquatable<ServicesDiscoveryResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServicesDiscoveryResponse" /> class.
        /// </summary>
        /// <param name="Apis">Apis.</param>
        public ServicesDiscoveryResponse(List<ServiceDiscoveryApiInfo> Apis = default(List<ServiceDiscoveryApiInfo>))
        {
            this.Apis = Apis;
        }
        
        /// <summary>
        /// Gets or Sets Apis
        /// </summary>
        [DataMember(Name="apis", EmitDefaultValue=false)]
        public List<ServiceDiscoveryApiInfo> Apis { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServicesDiscoveryResponse {\n");
            sb.Append("  Apis: ").Append(Apis).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServicesDiscoveryResponse);
        }

        /// <summary>
        /// Returns true if ServicesDiscoveryResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ServicesDiscoveryResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServicesDiscoveryResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Apis == input.Apis ||
                    this.Apis != null &&
                    this.Apis.SequenceEqual(input.Apis)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Apis != null)
                    hashCode = hashCode * 59 + this.Apis.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
