/* 
 * Discovery API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model.Discovery
{
    /// <summary>
    /// ServiceDiscoveryApiInfo
    /// </summary>
    [DataContract]
    public partial class ServiceDiscoveryApiInfo :  IEquatable<ServiceDiscoveryApiInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceDiscoveryApiInfo" /> class.
        /// </summary>
        /// <param name="Api">Api.</param>
        /// <param name="BaseUri">BaseUri.</param>
        public ServiceDiscoveryApiInfo(string Api = default(string), string BaseUri = default(string))
        {
            this.Api = Api;
            this.BaseUri = BaseUri;
        }
        
        /// <summary>
        /// Gets or Sets Api
        /// </summary>
        [DataMember(Name="api", EmitDefaultValue=false)]
        public string Api { get; set; }

        /// <summary>
        /// Gets or Sets BaseUri
        /// </summary>
        [DataMember(Name="baseUri", EmitDefaultValue=false)]
        public string BaseUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceDiscoveryApiInfo {\n");
            sb.Append("  Api: ").Append(Api).Append("\n");
            sb.Append("  BaseUri: ").Append(BaseUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceDiscoveryApiInfo);
        }

        /// <summary>
        /// Returns true if ServiceDiscoveryApiInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceDiscoveryApiInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceDiscoveryApiInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Api == input.Api ||
                    (this.Api != null &&
                    this.Api.Equals(input.Api))
                ) && 
                (
                    this.BaseUri == input.BaseUri ||
                    (this.BaseUri != null &&
                    this.BaseUri.Equals(input.BaseUri))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Api != null)
                    hashCode = hashCode * 59 + this.Api.GetHashCode();
                if (this.BaseUri != null)
                    hashCode = hashCode * 59 + this.BaseUri.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
