/* 
 * Discovery API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model.Discovery;

namespace IO.Swagger.Api.Discovery
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServicesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ServicesDiscoveryResponse</returns>
        ServicesDiscoveryResponse GetAooServiceApi (Guid? aooUID, string serviceUID, string xAuthorization);

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ServicesDiscoveryResponse</returns>
        ApiResponse<ServicesDiscoveryResponse> GetAooServiceApiWithHttpInfo (Guid? aooUID, string serviceUID, string xAuthorization);
        /// <summary>
        /// Returns a list of api endpoints for a specified global service
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ServicesDiscoveryResponse</returns>
        ServicesDiscoveryResponse GetGlobalServiceApi (string xAuthorization);

        /// <summary>
        /// Returns a list of api endpoints for a specified global service
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ServicesDiscoveryResponse</returns>
        ApiResponse<ServicesDiscoveryResponse> GetGlobalServiceApiWithHttpInfo (string xAuthorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ServicesDiscoveryResponse</returns>
        System.Threading.Tasks.Task<ServicesDiscoveryResponse> GetAooServiceApiAsync (Guid? aooUID, string serviceUID, string xAuthorization);

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ServicesDiscoveryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServicesDiscoveryResponse>> GetAooServiceApiAsyncWithHttpInfo (Guid? aooUID, string serviceUID, string xAuthorization);
        /// <summary>
        /// Returns a list of api endpoints for a specified global service
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ServicesDiscoveryResponse</returns>
        System.Threading.Tasks.Task<ServicesDiscoveryResponse> GetGlobalServiceApiAsync (string xAuthorization);

        /// <summary>
        /// Returns a list of api endpoints for a specified global service
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ServicesDiscoveryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServicesDiscoveryResponse>> GetGlobalServiceApiAsyncWithHttpInfo (string xAuthorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ServicesApi : IServicesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServicesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ServicesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServicesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ServicesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ServicesDiscoveryResponse</returns>
        public ServicesDiscoveryResponse GetAooServiceApi (Guid? aooUID, string serviceUID, string xAuthorization)
        {
             ApiResponse<ServicesDiscoveryResponse> localVarResponse = GetAooServiceApiWithHttpInfo(aooUID, serviceUID, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ServicesDiscoveryResponse</returns>
        public ApiResponse< ServicesDiscoveryResponse > GetAooServiceApiWithHttpInfo (Guid? aooUID, string serviceUID, string xAuthorization)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling ServicesApi->GetAooServiceApi");
            // verify the required parameter 'serviceUID' is set
            if (serviceUID == null)
                throw new ApiException(400, "Missing required parameter 'serviceUID' when calling ServicesApi->GetAooServiceApi");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ServicesApi->GetAooServiceApi");

            var localVarPath = "/api/v1/discovery/aoos/{aooUID}/services/{serviceUID}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (serviceUID != null) localVarPathParams.Add("serviceUID", Configuration.ApiClient.ParameterToString(serviceUID)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooServiceApi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServicesDiscoveryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServicesDiscoveryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServicesDiscoveryResponse)));
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ServicesDiscoveryResponse</returns>
        public async System.Threading.Tasks.Task<ServicesDiscoveryResponse> GetAooServiceApiAsync (Guid? aooUID, string serviceUID, string xAuthorization)
        {
             ApiResponse<ServicesDiscoveryResponse> localVarResponse = await GetAooServiceApiAsyncWithHttpInfo(aooUID, serviceUID, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a list of api endpoints for a specified service and aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aooUID">Aoo unique identifier</param>
        /// <param name="serviceUID">Service unique identifier</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ServicesDiscoveryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServicesDiscoveryResponse>> GetAooServiceApiAsyncWithHttpInfo (Guid? aooUID, string serviceUID, string xAuthorization)
        {
            // verify the required parameter 'aooUID' is set
            if (aooUID == null)
                throw new ApiException(400, "Missing required parameter 'aooUID' when calling ServicesApi->GetAooServiceApi");
            // verify the required parameter 'serviceUID' is set
            if (serviceUID == null)
                throw new ApiException(400, "Missing required parameter 'serviceUID' when calling ServicesApi->GetAooServiceApi");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ServicesApi->GetAooServiceApi");

            var localVarPath = "/api/v1/discovery/aoos/{aooUID}/services/{serviceUID}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aooUID != null) localVarPathParams.Add("aooUID", Configuration.ApiClient.ParameterToString(aooUID)); // path parameter
            if (serviceUID != null) localVarPathParams.Add("serviceUID", Configuration.ApiClient.ParameterToString(serviceUID)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooServiceApi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServicesDiscoveryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServicesDiscoveryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServicesDiscoveryResponse)));
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified global service 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ServicesDiscoveryResponse</returns>
        public ServicesDiscoveryResponse GetGlobalServiceApi (string xAuthorization)
        {
             ApiResponse<ServicesDiscoveryResponse> localVarResponse = GetGlobalServiceApiWithHttpInfo(xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified global service 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of ServicesDiscoveryResponse</returns>
        public ApiResponse< ServicesDiscoveryResponse > GetGlobalServiceApiWithHttpInfo (string xAuthorization)
        {
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ServicesApi->GetGlobalServiceApi");

            var localVarPath = "/api/v1/discovery/services";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGlobalServiceApi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServicesDiscoveryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServicesDiscoveryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServicesDiscoveryResponse)));
        }

        /// <summary>
        /// Returns a list of api endpoints for a specified global service 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ServicesDiscoveryResponse</returns>
        public async System.Threading.Tasks.Task<ServicesDiscoveryResponse> GetGlobalServiceApiAsync (string xAuthorization)
        {
             ApiResponse<ServicesDiscoveryResponse> localVarResponse = await GetGlobalServiceApiAsyncWithHttpInfo(xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a list of api endpoints for a specified global service 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (ServicesDiscoveryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServicesDiscoveryResponse>> GetGlobalServiceApiAsyncWithHttpInfo (string xAuthorization)
        {
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling ServicesApi->GetGlobalServiceApi");

            var localVarPath = "/api/v1/discovery/services";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGlobalServiceApi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServicesDiscoveryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServicesDiscoveryResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServicesDiscoveryResponse)));
        }

    }
}
